### ISSUE TITLE
100% Horizontal progress not filling all the way up

### ISSUE THREAD

**Issue by eni9889** [chasseurmic/TWRProgressView#2]
This is the original mask:
![progress](https://cloud.githubusercontent.com/assets/360222/4312982/4a374f58-3ec1-11e4-9e27-9c04b123c843.png)

And here is the result:

![2014-09-17 16 19 25](https://cloud.githubusercontent.com/assets/360222/4312976/3692630c-3ec1-11e4-9bc6-a1818ad48745.png)

Would love any help

**Comment by chasseurmic** [comment]
I have downloaded your masking image and set up an Xcode project to try it out and I didn't find any problems with it. I set up a view in Interface Builder and using the following code in my view controller:

``` objc
@property (weak, nonatomic) IBOutlet TWRProgressView *progressView;

[self.progressView setMaskingImage:[UIImage imageNamed:@"progress"]];
[self.progressView setProgress:1.0f];
```

Here's the output:
![screenshot 2014-09-22 22 24 22](https://cloud.githubusercontent.com/assets/1525833/4363520/953931f0-4296-11e4-956a-ca062fc76704.png)

**Comment by eni9889** [comment]
Hi,

Is this on iOS 8? Because I also set the view up on IB and got the results u see on the original comment

**Comment by chasseurmic** [comment]
Yes

**Comment by eni9889** [comment]
That is very strange. Can you send me your xcode project?
